# Generated by Django 5.0.6 on 2024-10-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_purchase_purchase_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
